### ISSUE TITLE
Build error on latest released version

### ISSUE THREAD

**Issue by twelvelabs** [boyter/gocodewalker#4]
I added `gocodewalker` to my project and got a build error:

```shell
$ go get github.com/boyter/gocodewalker
$ go build .
# github.com/boyter/gocodewalker
../../../go/pkg/mod/github.com/boyter/gocodewalker@v1.2.0/file.go:294:23: cannot use file (variable of type fs.FileInfo) as fs.DirEntry value in argument to IsHidden: fs.FileInfo does not implement fs.DirEntry (missing method Info)
../../../go/pkg/mod/github.com/boyter/gocodewalker@v1.2.0/file.go:431:23: cannot use dir (variable of type fs.FileInfo) as fs.DirEntry value in argument to IsHidden: fs.FileInfo does not implement fs.DirEntry (missing method Info)
```

Downgrading to `v1.1.1` works:

```shell
$ go get github.com/boyter/gocodewalker@v1.1.1
go: downgraded github.com/boyter/gocodewalker v1.2.0 => v1.1.1
$ go build .
```

Looks like there's a disparity between [pkg.go.dev](https://pkg.go.dev/github.com/boyter/gocodewalker?tab=versions) and your tags. Perhaps the `v1.2.0` tag was deleted? If so, you'll need to add [a `retract` line to your go.mod file](https://stackoverflow.com/questions/68599703/how-do-i-delete-a-package-that-i-accidentally-published-to-go-dev) and push a new version to prevent `v1.2.0` from being downloaded.

**Comment by boyter** [comment]
Sorry totally missed this in my notifications some how. Merged.
